name: Test and Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_SUITE_ID: ${{ secrets.TEST_SUITE_ID }}
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    steps:
      - name: Trigger Test Suite
        id: trigger_test_suite
        run: |
          response=$(curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" \
            -X POST "https://lcnc-api.browserstack.com/api/v1/test-suite/${TEST_SUITE_ID}/run")
          echo "Response: $response"

          BUILD_ID=$(echo "$response" | jq -r '.build_id')
          echo "Extracted BUILD_ID: $BUILD_ID"

          echo "BUILD_ID=$BUILD_ID" >> $GITHUB_ENV

      - name: Check Build Status
        run: |
          echo "Using BUILD_ID: $BUILD_ID"

          buildStatus=""
          retryInterval=30

          while [[ "$buildStatus" != "passed" && "$buildStatus" != "failed" ]]; do
            response=$(curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" \
              -s "https://lcnc-api.browserstack.com/api/v1/builds/${BUILD_ID}/status")
            buildStatus=$(echo "$response" | jq -r '.build_status')
            echo "Current Status: $buildStatus"
            sleep $retryInterval
          done

          if [[ "$buildStatus" == "passed" ]]; then
            echo "✅ Build passed"
          else
            echo "❌ Build failed"
            exit 1
          fi

