name: Test and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Test Suite
        id: trigger_test_suite
        run: |
          echo "Triggering test suite: $TEST_SUITE_ID"

          response=$(curl -s -w "\nHTTP_STATUS:%{http_code}" \
            -u "jeswin_RrH40p:9TyqK4kTrq7aavs65XL8" \
            -X POST "https://lcnc-api.browserstack.com/api/v1/test-suite/2a83dd99d9a8782f1d2713e4d652c01f38dfd0f2/run" \
            -H "Content-Type: application/json" \
            -d "{\"base_url\": \"https://www.browserstack.com/\"}")

          # Separate body and status code
          body=$(echo "$response" | sed -n '/^HTTP_STATUS:/!p')
          status=$(echo "$response" | sed -n 's/^HTTP_STATUS://p')

          echo "HTTP Status: $status"
          echo "Response Body: $body"

          # Check if request was successful
          if [ "$status" -ne 200 ]; then
            echo "❌ Failed to trigger test suite. Status: $status"
            exit 1
          fi

          # Extract build_id from response
          BUILD_ID=$(echo "$body" | jq -r '.build_id')

          if [[ "$BUILD_ID" == "null" || -z "$BUILD_ID" ]]; then
            echo "❌ Error: build_id not found in response"
            exit 1
          fi

          echo "✅ Extracted BUILD_ID: $BUILD_ID"
